services:
  database:
    image: postgres:16.1-alpine3.18
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./dev-db:/docker-entrypoint-initdb.d:ro
    ports:
      - ${DB_PORT}:5432
